blank_issues_enabled: false
contact_links:
  - name: â›” Issues are disabled
    url: https://github.com/Ezharjan/url
    about: Please do not open issues. This repository does not accept public issues.
